### ISSUE TITLE
Support GCP Workload Identity in the repository-gcs plugin

### ISSUE THREAD

**Issue by davidchong-glean** [opensearch-project/OpenSearch#11224]
**Is your feature request related to a problem? Please describe.**
Storing snapshots with the repository-gcs plugin requires a gcp service account key that's stored as a kubernetes secret. We'd like to avoid this secret as it requires additional overhead like periodically rotating the secret for security. GCP's Workload Identity feature would be a better alternative that avoids the need for a secret. 

**Describe the solution you'd like**
Use GCP's workload identity feature for authentication in the repository-gcs plugin. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jazzlyn** [comment]
:wave: @davidchong-glean,
we use the repository-gcs plugin with workload identity. depends on your setup but maybe this helps with configuration, it works similar with opensearch: https://github.com/elastic/cloud-on-k8s/issues/5230#issuecomment-1005712536

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/RasonJ) [3](https://github.com/dbwiddis) [4](https://github.com/kotwanikunal) [5](https://github.com/Mahima081)]
@davidchong-glean Thanks for filing this issue, we would welcome a pull request to add this functionality.

**Comment by FredericJames** [comment]
This capability alongside the projected volume one [#459](https://github.com/opensearch-project/opensearch-k8s-operator/issues/459)
would be really convenient to be compliant with managed k8s way of managing cloud resources permissions.

**Comment by Bukhtawar** [comment]
We welcome a pull request. Maybe we just need to add standard GCP credential provider to the repository gcp
[Storage Triage - attendees [1](https://github.com/reta/) [2](https://github.com/linuxpi/) [3](https://github.com/sachinpkale/) [4](https://github.com/bukhtawar) [5](https://github.com/skumawat2025/) [6](https://github.com/BhumikaSaini-Amazon/) [7](https://github.com/ashking94/) [8](https://github.com/ltaragi/) [9](https://github.com/rwali-aws) [10](https://github.com/lukas-vlcek/)

**Comment by sachinpkale** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/hasnain2808) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/TODO) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon) [10](https://github.com/ltaragi) ]

Moved to `Ready to be picked`

**Comment by vinodhreddyg** [comment]
@sachinpkale : Can you please provide an ETA?

**Comment by sachinpkale** [comment]
@vinodhreddyg I am not working on it. As OpenSearch is community driven project, contributions are welcome.

**Comment by darjisagar7** [comment]
I would like to take this task up.

**Comment by dbwiddis** [comment]
@darjisagar7 assigned it to you!  Let us know if you need any help!

**Comment by vinodhreddyg** [comment]
If opensearch’s general.serviceaccount is populated and workload identity
is setup for the KSA and GSA. It works.

Regards,
Vinodh.

**Comment by dguendisch** [comment]
@vinodhreddyg did you really got this running in opensearch (and not elasticsearch)?

According to https://github.com/elastic/cloud-on-k8s/issues/5230#issuecomment-1008877065 this resp. PR was required for working workload ID support: https://github.com/elastic/elasticsearch/pull/71239. However that PR came after opensearch was forked and thus is missing in https://github.com/opensearch-project/OpenSearch/blob/3.1.0/plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java.

**Comment by ConnorsApps** [comment]
### Workaround
One way to get around this is to create a service account key and mount that into your container.

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: service-account-name
  annotations:
    cnrm.cloud.google.com/project-id: your-project-id
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: service-account-name-key
  annotations:
    cnrm.cloud.google.com/project-id: your-project-id
spec:
  publicKeyType: TYPE_X509_PEM_FILE
  privateKeyType: TYPE_GOOGLE_CREDENTIALS_FILE
  serviceAccountRef:
    name: service-account-name
```

Here's how to mount if using the OpenSearch operator.
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
spec:
  general:
    additionalVolumes:
    - name: workload-identity-credentials
      path: "/usr/share/opensearch/config/credentials"
      secret:
        defaultMode: 0655
        secretName: service-account-name-key
  nodePools:
  - env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
       value: "/usr/share/opensearch/config/credentials/key.json"
```
