### ISSUE TITLE
[BUG]The ECS task or the Opensearch dashboards' docker-compose.yml file doesn't recognize SAML configs

### ISSUE THREAD

**Issue by madhankb** [opensearch-project/OpenSearch#11528]
**Describe the bug**
When connecting a standalone OpenSearch dashboards with the SAML authenticated managed service domain, the SAML configurations are not accepted in the ECS task or in the docker-compose.yml file.

**To Reproduce**
1. Create a OpenSearch dashboards ECS task or docker-compose.yml file like below
````yaml
version: '3'
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      opensearch.hosts: '["https://vpc-saml-2-3cue34.ap-south-1.es.amazonaws.com"]'
      opensearch.username: 'xxx'
      opensearch.password: 'xxxx'
      opensearch_security.auth.type: "saml"
      server.xsrf.allowlist: ["/_opendistro/_security/saml/acs"]
    networks:
      - opensearch-net
networks:
  opensearch-net:
````

**Expected behavior**
When the standalone OSD endpoint is hit, it has to go to SAML application instead it goes to the dashboards home page and requires the customer to enter basic http username and password.
