### ISSUE TITLE
[Feature Request] Define GitHub labels in a file in source control

### ISSUE THREAD

**Issue by andrross** [opensearch-project/OpenSearch#12572]
### Is your feature request related to a problem? Please describe

GitHub labels can be added and removed by repo admins, but there's no clear process for how new labels get added or removed. If they were defined in a file in source control, then label additions/removals could happen via the PR process. Any contributor could propose a change and that could be discussed via the PR.

### Describe the solution you'd like

There is a GitHub action that provides this functionality: https://github.com/marketplace/actions/manage-github-labels

### Related component

Other

**Comment by dblock** [comment]
This would be awesome project-wide.

**Comment by bbarani** [comment]
@andrross  this is a good suggestion but maintainers should be able to create new labels as well and they don’t need to rely on admin.

**Comment by cwperks** [comment]
I like this idea. It would be helpful to add the `backport X.Y` label to all of the components when the version increment runs.

**Comment by Pallavi-AWS** [comment]
@andrross how can we use this source control based labeling to define a base set of labels at the project level? All repos should inherit those labels for consistency - in addition, repo maintainers can define a few extra labels at their repo level.

**Comment by andrross** [comment]
@Pallavi-AWS The quickest way I see to do this is to define the common labels in the `.github` repo, then each repo in the project adds a github action like the following:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Synchronize labels
        uses: julbme/gh-action-manage-label@v1
        with:
          from: |
            https://raw.githubusercontent.com/my-org/my-repositorty/path-to-folder-with/common-labels.yml
            .github/config/labels.yml
            .github/config/other-labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

where the `https://raw.githubusercontent.com/my-org/my-repositorty/path-to-folder-with/common-labels.yml` file is the common file defined in the .github repo.

This should be quick and easy, with the only hangup is that it has to happen in every repository.
