### ISSUE TITLE
[BUG] Operator does not recognize allowAutoCreate field in OpensearchComponentTemplate

### ISSUE THREAD

**Issue by ngc4579** [opensearch-project/OpenSearch#12937]
### What is the bug?

Assume the following `OpensearchComponentTemplate` similar (simplified) to the example in the operator [docs](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#managing-index-and-component-templates).

```
apiVersion: opensearch.opster.io/v1
kind: OpensearchComponentTemplate
metadata:
  name: default-component-template
spec:
  opensearchCluster:
    name: debezium-opensearch
  allowAutoCreate: true
  template:
    settings:
      number_of_shards: 2
      number_of_replicas: 1
  version: 1
```

The operator complains about not knowing the field `allow_auto_create` (note the snake case) and fails to apply the custom resource.

```
{"level":"error","ts":"2024-03-12T19:10:48.024Z","msg":"Reconciler error","controller":"opensearchcomponenttemplate","controllerGroup":"opensearch.opster.io","controllerKind":"OpensearchComponentTemplate","OpensearchComponentTemplate":{"name":"default-component-template","namespace":"debezium"},"namespace":"debezium","name":"default-component-template","reconcileID":"81b22205-6a54-4d5e-bfb9-c33fc7a84e30","error":"failed to create component template: [400 Bad Request] {\"error\":{\"root_cause\":[{\"type\":\"x_content_parse_exception\",\"reason\":\"[1:84] [component_template] unknown field [allow_auto_create]\"}],\"type\":\"x_content_parse_exception\",\"reason\":\"[1:84] [component_template] unknown field [allow_auto_create]\"},\"status\":400}","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
```

CR status:

```
Status:
Existing Component Template:  false
Managed Cluster:              2ee2433e-2983-4d4c-895f-2a8e0faf50e5
Reason:                       failed to update component template with OpenSearch API
State:                        ERROR
```

### How can one reproduce the bug?

See above example CR.

### What is your host/environment?

K8s 1.28.5, hosted environment. Opensearch Operator 2.51, installed via Helm / Argo CD.
