### ISSUE TITLE
[BUG] Suggested docker-compose.yml doesn't work with Docker Desktop for Windows, WSL2 mode

### ISSUE THREAD

**Issue by vivainio** [opensearch-project/OpenSearch#1325]
**Describe the bug**

In instructions stored at:

https://opensearch.org/downloads.html

It suggests to do this:

```
macOS & Windows: In Docker Preferences > Resources, set RAM to at least 4 GB.
```

However, this setting  is not available in WSL2 mode. 

When you do "docker-compose up", you get this error in the logs:

```
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

There is no "easy" way to do this in Docker Desktop, in WSL2 mode.

**To Reproduce**

0. Enable Docker Desktop WSL2 mode, as described in: https://docs.docker.com/desktop/windows/wsl/
1. Download https://opensearch.org/samples/docker-compose.yml
2. Do "docker-compose up" and follow the logs. You'll see that OpenSearch server crashes because of the error: " max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]"
 
**Expected behavior**

The example docker-compose.yml should work out of the box, also in Windows WSL2 mode. Possibly, there could be an environment variable to set that disables the initial check (allowing to at least test the application?)

Starting OpenSearch with environment variable discovery.type=single-node also avoids the crash

**Comment by vivainio** [comment]
The error is in no way particular to OpenSearch, it has been in ElasticSearch for a long time (see e.g. https://stackoverflow.com/questions/51445846/elasticsearch-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc). But maybe OpenSearch could finally fix it

**Comment by dblock** [comment]
@vivainio Want to suggest the preferred fix? Make a PR?

**Comment by vivainio** [comment]
@dblock I can't provide a preferred fix right away.

The "easy" fix would be to remove opensearch-node2 from docker-compose completely, and switch to discovery.type=single-node, but would that be too simple of a setup for demonstrating OpenSearch? Anyway, it would make it work on Windows after that

**Comment by vivainio** [comment]
Here's the contents of working docker-compose.yml:

```yaml
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```
