### ISSUE TITLE
Remote Configuration for Traces/Metrics GRPC

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/OpenSearch#13323]
### Is your feature request related to a problem? Please describe

The feature is required to send traces and metrics of opensearch to external monitoring tools like signoz.

- We have tested metrics and traces, it's working properly on a log file, and tested the grpc, and working fine, but we were not able to use a specific configuration for otlp to send those traces and metrics to signoz as an example.

- We checked the docs and noticed that it's not configurable. 
- We found a typo related to the grpc configuration for traces, the class in the docs is mentioned incorrectly ```telemetry.otel.tracer.span.exporter.class=org.opensearch.telemetry.tracing.exporter.OtlpGrpcSpanExporterProvider```, while it should have the following value ```telemetry.otel.tracer.span.exporter.class: io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter```
- Another note would be related to trace configuration, ```telemetry.feature.tracer.enabled: true``` this configuration is not mentioned in the docs, I got the support from @Gaganjuneja in another story [Metrics Framework](https://github.com/opensearch-project/OpenSearch/issues/10141#issuecomment-2063628340), and tested and it's working fine for the trace file log configuration.  

### Describe the solution you'd like

# There are 3 solutions 
1- Create a new environment variable for this case.
2- Reuse the environment variable featured by opentelemetry ```OTEL_EXPORTER_OTLP_ENDPOINT```.
3- Create a configmap or addition **opensearch.yml** configuration. 

### Related component

Plugins

### Describe alternatives you've considered

The alternative solution now is to use a reverse proxy for rerouting / redirecting traffic to a remote otel-collector server, but I believe it's not practical and I would not use it within Kubernetes cluster deployment.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/kotwanikunal) [3](https://github.com/vikasvb90) [4](https://github.com/mch2) [5](https://github.com/jed326) [6](https://github.com/dbwiddis) [7](https://github.com/scrawfor99)]
@zalseryani Thanks for creating this issue, note this is a little high level - it isn't exactly clear how this would happen or if there is good patterns for reuse elsewhere in OpenSearch.  Pull requests might see some extra design discussion that would be good to head off with an RFC- for your consideration.

**Comment by Gaganjuneja** [comment]
@zalseryani thanks for opening this issue. 

1. For distributed tracing documentation fix, I have created an [issue](https://github.com/opensearch-project/documentation-website/issues/7028) and will address that.
2. To support configuring the exported end point, we already had discussion and I need to revive [this thread](https://github.com/opensearch-project/OpenSearch/pull/9666#discussion_r1315987695) with the best possible option. issue - https://github.com/opensearch-project/OpenSearch/issues/9764

**Comment by tylerlittlefield** [comment]
I'm running:

* Chart version: `2.27.0`
* Image tags: `2.19.4`

Just wanted to check my understanding. Is it possible to take a configuration like so:

```yaml
plugins:
  enabled: true
  installList: 
  - telemetry-otel

config:
  opensearch.yml: |
    cluster.name: opensearch
    node.name: ${HOSTNAME}
    discovery.seed_hosts: ["opensearch-master-headless"]
    cluster.initial_master_nodes: ["opensearch-master-0","opensearch-master-1","opensearch-master-2"]

    # metrics configuration
    search.query.metrics.enabled: true
    telemetry.feature.metrics.enabled: true

    # open telemetry traces configuration
    opensearch.experimental.feature.telemetry.enabled: true
    telemetry.tracer.sampler.probability: 1.0
    telemetry.feature.tracer.enabled: true
    telemetry.otel.tracer.span.exporter.class: io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter

extraEnvs:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://alloy.alloy.svc.cluster.local:4317"
```

So that I can send OpenSearch traces to alloy, alloy to tempo, and then visualize traces in grafana ui?
