### ISSUE TITLE
[BUG] very slow docker boot start on v2.13.0

### ISSUE THREAD

**Issue by bodinsamuel** [opensearch-project/OpenSearch#13418]
### Describe the bug

Hey,

Recently started using opensearch with docker, and noticed a very slow boot time after upgrading to 2.13.0.
It went from ~10s boot time to ~100s with the exact same configuration. 

### Related component

Other

### To Reproduce

```yaml
version: '3.9'
services:
    opensearch:
        container_name: opensearch
        image: opensearchproject/opensearch:2.13.0
        volumes:
            - opensearch-data1:/usr/share/opensearch/data
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - DISABLE_SECURITY_PLUGIN=true

volumes:
    opensearch-data1:
        driver: local
```

- `docker compose up -d`
- localhost:9200 will only respond after more than a minute

### Expected behavior

boot faster :D
