### ISSUE TITLE
[BUG] github action service fails with "Error: Could not find or load main class Cannot"

### ISSUE THREAD

**Issue by mrkamel** [opensearch-project/OpenSearch#13781]
### Describe the bug

In our github action which start an opensearch instance we often (every 20-30th run) see the opensearch container fail with 2.11, 2.12 and also 2.13. Excerpt from our action config:

```yaml
    services:
      opensearch:
        image: opensearchproject/opensearch:2.13.0
        env:
          discovery.type: single-node
          plugins.security.disabled: "true"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: "..."
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 10
```

Pipeline output:

```
Service container opensearch failed.
  /usr/bin/docker logs --details 963fd41d9172b63f2402f48bd758b9d5b31bba6b30c4201e88c89496fc73b27c
   Enabling OpenSearch Security Plugin
   WARNING: java.io.tmpdir directory does not exist
   Error: Could not find or load main class Cannot
   Caused by: java.lang.ClassNotFoundException: Cannot
   Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin 
   OpenSearch 2.12.0 onwards, the OpenSearch Security Plugin a change that requires an initial password for 'admin' user. 
   Please define an environment variable 'OPENSEARCH_INITIAL_ADMIN_PASSWORD' with a strong password string. 
   If a password is not provided, the setup will quit. 
    For more details, please visit: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
   ### OpenSearch Security Demo Installer
   ### ** Warning: Do not use on production or public reachable systems **
   OpenSearch install type: rpm/deb on Linux 6.1.79-99.167.amzn2023.x86_64 amd64
   OpenSearch config dir: /usr/share/opensearch/config/
   OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
   OpenSearch bin dir: /usr/share/opensearch/bin/
   OpenSearch plugins dir: /usr/share/opensearch/plugins/
   OpenSearch lib dir: /usr/share/opensearch/lib/
   Detected OpenSearch Version: 2.13.0
   Detected OpenSearch Security Version: 2.13.0.0
   Admin password set successfully.
   ### Success
   ### Execute this script now on all your nodes and then start all nodes
   ### OpenSearch Security will be automatically initialized.
   ### If you like to change the runtime configuration 
   ### change the files in ../../../config/opensearch-security and execute: 
   sudo "/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh" -cd "/usr/share/opensearch/config/opensearch-security" -icl -key "/usr/share/opensearch/config/kirk-key.pem" -cert "/usr/share/opensearch/config/kirk.pem" -cacert "/usr/share/opensearch/config/root-ca.pem" -nhnv
   ### or run ./securityadmin_demo.sh
   ### To use the Security Plugin ConfigurationGUI
   ### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/<your-custom-admin-password>.
   ### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
   Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
  Error: Failed to initialize container opensearchproject/opensearch:2.13.0
Error: One or more containers failed to start.
```

### Related component

Search

### To Reproduce

1. Have a github action starting opensearch
2. run the action often times
3. See error

### Expected behavior

The container never fails to start
