### ISSUE TITLE
[BUG] Security Plugin Disabled Still Requires HTTPS

### ISSUE THREAD

**Issue by dorzgi** [opensearch-project/OpenSearch#1405]
**Describe the bug**
Hello,
I'm trying to setup the docker image locally for testing and integration.
I've created a custom `opensearch.yml` and i've created a mount to the following path: `/usr/share/opensearch/config/opensearch.yml`

The contents of the file are:
```yaml
cluster.name: greeninvoice
action.auto_create_index: true
compatibility.override_main_response_version: true
plugins.security.disabled: true
```

The contents of the `docker-compose.yml` are:
```yaml
  elastic:
    image: opensearchproject/opensearch:1.0.0
    container_name: elastic-search
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
    volumes:
      - ./infra/elastic/conf/elastic-custom.yml:/usr/share/opensearch/config/opensearch.yml
      - ./data/elastic:/usr/share/opensearch/data
      - ./logs/elastic:/usr/share/opensearch/logs
```

However once i'm running the `docker-compose.yml` and i'm trying to use cURL to put a template i get the following error:
```
curl: (52) Empty reply from server
```

The command i'm trying to execute is:
```bash
curl -XPUT "http://localhost:9200/_template/clients" -H "Content-Type: application/json" -d '{"index_patterns":["clients_v3*"],"settings":{"number_of_shards":1,"number_of_replicas":0,"analysis":{"normalizer":{"sort_normalizer":{"type":"custom","filter":["lowercase","asciifolding"]}}}},"mappings":{"dynamic":"strict","properties":{"creationDate":{"type":"date","format":"date_optional_time"},"lastUpdateDate":{"type":"date","format":"date_optional_time"},"businessId":{"type":"keyword"},"name":{"type":"text","fields":{"raw":{"type":"keyword","normalizer":"sort_normalizer"}}},"country":{"type":"keyword"},"status":{"type":"short"}}}}'
```

Am I missing something?

**To Reproduce**
See the description.

**Expected behavior**
I expect once i'm disabling the security plugin i will be able to use http.

**Plugins**
The default ones, excluding the security plugin.

**Screenshots**
...

**Host/Environment (please complete the following information):**
 - OS: macOS
 - Version BigSur 11.6

**Additional context**
Thanks.

**Comment by dorzgi** [comment]
Anyone?

**Comment by IMS94** [comment]
@dorzgi I just tried again and it works for me. Following is my setup.

**Docker Compose file**
```
version: "3.9"

services:
  opensearch:
    image: opensearchproject/opensearch:1.1.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - "9200:9200"
      - "9600:9600"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'

volumes:
  opensearch-data:
```
You can ignore the `opensearch-dashboards` service if not required.

**opensearch.yml file**
```yaml
cluster.name: docker-cluster
network.host: 0.0.0.0
plugins.security.disabled: true
```

Once started with `docker-compose up -d` and tried the following curl command, it works fine:
```
curl -v http://localhost:9200
```
and the output is:
```
imesha@imesha:~$ curl -v http://localhost:9200
*   Trying 127.0.0.1:9200...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 568
< 
{
  "name" : "da5caf55d157",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "nZMZeL5iQ4W6Zooy0t736w",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.1.0",
    "build_type" : "tar",
    "build_hash" : "15e9f137622d878b79103df8f82d78d782b686a1",
    "build_date" : "2021-10-04T21:29:03.079792Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
* Connection #0 to host localhost left intact
```
And `curl -v https://localhost:9200` will not work (HTTPS url)
