### ISSUE TITLE
[BUG] Arrays of `geo_shape` are broken after v2.8.0

### ISSUE THREAD

**Issue by kurtmckee** [opensearch-project/OpenSearch#14193]
### Describe the bug

While investigating whether a product I work on could migrate from ElasticSearch to OpenSearch, I found that OpenSearch support for ingesting arrays of `geo_shape` objects is broken after v2.8.0.

Specifically, the error message I get back during ingest is:

```json
{
  "error" : {
    "type" : "illegal_argument_exception",
    "reason" : "DocValuesField \"location\" appears more than once in this document (only one value is allowed per field)"
  }
}
```

I created a YAML test and used `git bisect` between v2.8.0 and v2.9.0 commits to track the issue to commit `ebe6f2c2878f036cb4c1147683c30091747d7632`, introduced in PRs #4266 and #8301.

### Related component

Other

### To Reproduce

> [!NOTE]
> 
> I've opened PR #14196 using a branch containing the YAML test file that demonstrates this issue. An OpenSearch maintainer can pull the changes, add fix commits, and push back to the associated PR.

I'm running the test suite using the following command with an additional YAML file that demonstrates the problem.

```
./gradlew :modules:geo:yamlRestTest
```

YAML file location:

```
modules/geo/src/yamlRestTest/resources/rest-api-spec/test/geo_shape/300_array_of_geo_shapes.yml
```

YAML file contents (with comments added only here):

<details><summary>Details</summary>
<p>

```yaml
setup:
  - do:
      indices.create:
        index: test
        body:
          settings:
            number_of_replicas: 0
          mappings:
            properties:
              location:
                type: "geo_shape"

---
# This works across all git commits in 2.8.0..2.9.0
"Single shape":
  - do:
      bulk:
        refresh: true
        body:
          - index:
              _index: test
              _id: 1
          - location:
              type: "polygon"
              coordinates: [
                [
                  [ -87.0, 41.0 ],
                  [ -88.0, 41.0 ],
                  [ -88.0, 42.0 ],
                  [ -87.0, 42.0 ],
                  [ -87.0, 41.0 ],
                ]
              ]

  - match: {errors: false}

---
# This fails starting at commit ebe6f2c2878f036cb4c1147683c30091747d7632
"Array of shapes":
  - do:
      bulk:
        refresh: true
        body:
          - index:
              _index: test
              _id: 1
          - location:
              - type: "polygon"
                coordinates: [
                  [
                    [ -87.0, 41.0 ],
                    [ -88.0, 41.0 ],
                    [ -88.0, 42.0 ],
                    [ -87.0, 42.0 ],
                    [ -87.0, 41.0 ],
                  ]
                ]
              - type: "polygon"
                coordinates: [
                  [
                    [ -97.0, 41.0 ],
                    [ -98.0, 41.0 ],
                    [ -98.0, 42.0 ],
                    [ -97.0, 42.0 ],
                    [ -97.0, 41.0 ],
                  ]
                ]

  - match: {errors: false}
```

</p>
</details> 

### Expected behavior

I expected that I could creating a "location" field with a `geo_shape` mapping and then ingest an array of `geo_shape` objects. The product I work on uses ElasticSearch 7.10 and arrays of `geo_shape` objects can be ingested, and this also is [how arrays are documented to work](https://opensearch.org/docs/latest/field-types/supported-field-types/index/#arrays):

> There is no dedicated array field type in OpenSearch. Instead, you can pass an array of values into any field.

### Additional Details

None. I'm just running the test suite with an additional YAML file.
