### ISSUE TITLE
[BUG] "java.lang.IllegalArgumentException: -84 is not a valid id"

### ISSUE THREAD

**Issue by uranru** [opensearch-project/OpenSearch#14632]
### Describe the bug

I use logstash to load data in Openserach.
After updating the version (2.13 -> 2.15) on several nodes, I began to receive this error.

### Related component

Other

### To Reproduce

Logstash (logstash:8.13.1) sends data to Opensearch.

### Expected behavior

No errors when loading data

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by mgodwan** [comment]
Thanks @uranru for reporting this.

1. Could you share the complete stack trace you're seeing for this in your opensearch cluster?
2. Do you have security enabled for your OpenSearch cluster?

**Comment by uranru** [comment]
@mgodwan 
I see these events in the logs:

```
[2024-07-03T13:38:30,029][INFO ][logstash.outputs.opensearch][db-pgbouncer][df97c6871c75b7619f5d19d9becaa589840f886a88ab802122079f6b3e55c614] Retrying failed action {:status=>500, :action=>["index", {:_id=>nil, :_index=>"db-pgbouncer-2024.07.02", :routing=>nil}, {"host"=>{"name"=>"db", "domain"=>"prod"}, "log"=>{"name"=>"pgbouncer", "time"=>2024-07-02T21:00:25.758Z, "file"=>{"path"=>"/var/log/postgresql/pgbouncer.log"}}, "tags"=>["pgbouncer", "prod", "_grokparsefailure"], "@version"=>"1", "processing"=>{"host"=>"logstash04", "timestamp"=>2024-07-02T21:00:30.879200Z, "delay"=>5.1}, "message"=>"2024-07-03 00:00:20.511 MSK [1133] WARNING could not parse hba config line 9", "@timestamp"=>2024-07-02T21:00:25.758Z, "app"=>{"name"=>"pgbouncer", "group"=>"db"}, "alert"=>"false"}], :error=>{"type"=>"exception", "reason"=>"java.lang.IllegalArgumentException: -84 is not a valid id", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"-84 is not a valid id"}}}

[2024-07-03T13:38:30,029][INFO ][logstash.outputs.opensearch][db-pgbouncer][df97c6871c75b7619f5d19d9becaa589840f886a88ab802122079f6b3e55c614] Retrying failed action {:status=>500, :action=>["index", {:_id=>nil, :_index=>"db-pgbouncer-2024.07.02", :routing=>nil}, {"host"=>{"name"=>"db", "domain"=>"prod"}, "log"=>{"name"=>"pgbouncer", "time"=>2024-07-02T21:00:25.758Z, "file"=>{"path"=>"/var/log/postgresql/pgbouncer.log"}}, "tags"=>["pgbouncer", "prod", "_grokparsefailure"], "@version"=>"1", "processing"=>{"host"=>"logstash04", "timestamp"=>2024-07-02T21:00:30.879238Z, "delay"=>5.1}, "message"=>"2024-07-03 00:00:20.510 MSK [1133] LOG got SIGHUP, re-reading config", "@timestamp"=>2024-07-02T21:00:25.758Z, "app"=>{"name"=>"pgbouncer", "group"=>"db"}, "alert"=>true}], :error=>{"type"=>"exception", "reason"=>"java.lang.IllegalArgumentException: -84 is not a valid id", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"-84 is not a valid id"}}}
```

**Comment by uranru** [comment]
securityconfig/config.yml

```
_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal

      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            openid_connect_idp:
              enable_ssl: true
              verify_hostnames: false
              pemtrustedcas_filepath: /usr/share/opensearch/config/certificates/ca/ca.pem
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://idp.xxx.com:/realms/prodnt/.well-known/openid-configuration
        authentication_backend:
          type: noop
```
