### ISSUE TITLE
[BUG] can't login in dashboard running locally on docker

### ISSUE THREAD

**Issue by aterreno** [opensearch-project/OpenSearch#1558]
Hi there, 
 I am trying to login into dashboards from localhost, my docker-compose.yml is pretty vanilla like: 
 
 ```yaml
  opensearch:
    image: opensearchproject/opensearch:1.1.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_master_nodes=opensearch
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - opensearch.username="admin"
      - opensearch.password="admin"
    networks:
      - opensearch-net
      
  volumes:
    opensearch-data:  

networks:
  opensearch-net:
    driver: bridge   
 ```
 
 I checked on the container running the dashboards, 
 ```bash
 cat /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
 ```

```properties
server.host: "0"
opensearch.hosts: ["https://localhost:9200"]
opensearch.ssl.verificationMode: none
opensearch.username: "kibanaserver"
opensearch.password: "kibanaserver"
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
# Use this setting if you are running opensearch-dashboards without https
opensearch_security.cookie.secure: false
```

but on http://localhost:5601/app/login

entering kibanaserver:kibanaserver won't work, giving me back a 401

please note I am running opensearch with plugins.security.disabled=true, if it's any related at all. 

thanks
