### ISSUE TITLE
Needed: easy way to setup service as plain HTTP (for development)

### ISSUE THREAD

**Issue by vivainio** [opensearch-project/OpenSearch#1598]
I would like to set up OpenSearch container image in development environments using plain HTTP.

This does not work out of the box, as the service defaults to HTTPS and crashes when plain old HTTP connection is attempted.

**Describe the solution you'd like**

In docker-compose.yml, I would like to be able to say "security.usehttp=true" or somesuch, and things should just work.

**Describe alternatives you've considered**

I created a custom docker image, but opensearch-dashboards doesn't work with that. Dockerfile:

```
FROM opensearchproject/opensearch:1.1.0
RUN /usr/share/opensearch/bin/opensearch-plugin remove opensearch-security
COPY --chown=opensearch:opensearch custom-opensearch.yml /usr/share/opensearch/config/
```

I also tried mounting custom opensearch.yml, but this is somewhat tricky in Windows docker and opensearch-dashboards didn't work with it either.

Environment variables that can be passed directly in docker-compose.yml are WAY easier than complete custom config file, especially since you won't easily break other functionality while changing a single flag.

**Comment by IMS94** [comment]
Similar concern is discussed in #1393

**Comment by setiah** [comment]
@vivainio you can disable security (hence HTTPS) via docker environment variables when running docker by setting `plugins.security.disabled=true`. Running the below command worked for me on Mac, (haven't tried windows). It automatically pulled the docker image and spinned up a cluster with http access. 

Reference: How to disable security - https://opensearch.org/docs/latest/security-plugin/configuration/disable/

```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -e "plugins.security.disabled=true" opensearchproject/opensearch:1.1.0
```

I agree with your larger point on making the overall experience simpler.

**Comment by namrataa-p** [comment]
@vivainio I had similar requirements and following docker-compose.yml worked for me on Windows.
```
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:1.2.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
volumes:
  opensearch-data1:
networks:
  opensearch-net:
```

Found the `DISABLE_INSTALL_DEMO_CONFIG, DISABLE_SECURITY_PLUGIN, DISABLE_SECURITY_DASHBOARDS_PLUGIN` vars from [scenario-2-no-demo-certsconfigs--disable-security-on-both-opensearch-and-opensearch-dashboards](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/README.md#scenario-2-no-demo-certsconfigs--disable-security-on-both-opensearch-and-opensearch-dashboards)
