### ISSUE TITLE
[BUG] OPENSEARCH_INITIAL_ADMIN_PASSWORD doesn't work with opensearch:2.17.0 docker image

### ISSUE THREAD

**Issue by Tlecomte13** [opensearch-project/OpenSearch#16092]
### Describe the bug

In version **2.17** of the official OpenSearch Docker image, the environment variable `OPENSEARCH_INITIAL_ADMIN_PASSWORD` is not functioning as expected. When launching the container, OpenSearch prompts for an admin password despite the variable being set in the docker-compose.yml file. 

```
  opensearch-node:
    image: opensearchproject/opensearch:2.17.0
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=${NODE_NAME}
      - discovery.seed_hosts=${NODE_NAME}
      - cluster.initial_master_nodes=${NODE_NAME}
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
```

curl 
`curl -k -u admin:<password> https://localhost:9200`
`Unauthorized`

Using version 2.16 of the OpenSearch Docker image works perfectly fine, with the OPENSEARCH_INITIAL_ADMIN_PASSWORD variable being recognized correctly and allowing the container to start without issues.

```
curl -k -u admin:<password> https://localhost:9200
{
  "name" : "opensearch-node",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "dGE6WpovS7u-C8Y_qwhL1Q",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.16.0",
    "build_type" : "tar",
    "build_hash" : "f84a26e76807ea67a69822c37b1a1d89e7177d9b",
    "build_date" : "2024-08-06T20:32:34.547531562Z",
    "build_snapshot" : false,
    "lucene_version" : "9.11.1",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

### Related component

Build

### To Reproduce

1. Use the official OpenSearch Docker image version 2.17.
2. Set the environment variable OPENSEARCH_INITIAL_ADMIN_PASSWORD in the docker-compose.yml.
3. Start the container using docker-compose up.
4. try to curl https://localhost:9200

### Expected behavior

The container should start successfully without prompting for an admin password. It should utilize the password provided through the OPENSEARCH_INITIAL_ADMIN_PASSWORD environment variable, allowing access to the OpenSearch instance without any authentication issues.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: macos M3

**Additional context**
