### ISSUE TITLE
[BUG] [Streaming Indexing] Invalid chunk on error (missing newline)

### ISSUE THREAD

**Issue by thomas-long-f3** [opensearch-project/OpenSearch#17725]
### Describe the bug

While working on a streaming bulk client, I've intermittently hit deadlocks in my application. I believe I have narrowed it down to how chunks are returned for invalid requests. See example below.

### Related component

Indexing

### To Reproduce

I'm running OpenSearch 2.19.0 locally in docker, using the below configuration:

```Dockerfile
FROM opensearchproject/opensearch:2.19.0

RUN ./bin/opensearch-plugin install --batch transport-reactor-netty4
```
```yml
  opensearch:
    ports:
      - "9200:9200"
    build:
      context: opensearch
      dockerfile: OpenSearch.Dockerfile
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "http.type=reactor-netty4"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
      - "DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true" # Disables Performance Analyzer Plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    user: "1000:1000"
```

When sending a valid request...

```
curl -X POST "http://localhost:9200/_bulk/stream" -H "Transfer-Encoding: chunked" -H "Content-Type: application/json" -d'{"index":{"_index": "movies"}}
{"hello":"world"}
'
{"took":5,"errors":false,"items":[{"index":{"_index":"movies","_id":"iOBP3ZUBKrCw-AiSDcbj","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1,"status":201}}]}
```

When sending an invalid request (here the index is missing):

```
curl -X POST "http://localhost:9200/_bulk/stream" -H "Transfer-Encoding: chunked" -H "Content-Type: application/json" -d'{"index":{}}
{"hello":"world"}
'
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: index is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: index is missing;"},"status":400}%
```

Note the `%` from `zsh`, the response does not end in a newline. 

### Expected behavior

All responses are valid chunks.
