### ISSUE TITLE
[BUG] False version on stable release

### ISSUE THREAD

**Issue by alexander-schranz** [opensearch-project/OpenSearch#18224]
### Describe the bug

The outputted version in the stable 3.0.0 is 3.0.0-beta1

### To Reproduce

1.

```yml
services:
  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      discovery.type: single-node
      cluster.routing.allocation.disk.threshold_enabled: 'false'
      DISABLE_SECURITY_PLUGIN: true
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data:
```

2. `docker compose up`

3. outputted version still is beta:

![Image](https://github.com/user-attachments/assets/8215f8fb-c978-47e8-a98d-46d618a443c2)

### Expected behavior

The version should be 3.0.0

### Additional Details

**Plugins**

No

**Screenshots**

See above

**Host/Environment (please complete the following information):**
 - OS: MACOS via docker desktop
 - Version 3.0.0

**Additional context**
