### ISSUE TITLE
[BUG] Opensearch didn't start in docker

### ISSUE THREAD

**Issue by dontepanlin** [opensearch-project/OpenSearch#18412]
### Describe the bug

Absolutely normal compose file

```yaml
services:
  opensearch-node:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-node
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=<STRONG>" 
    volumes:
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/jvm.options:/usr/share/opensearch/config/jvm.options
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
volumes:
  opensearch-data:
```

### To Reproduce

docker compose up

### Expected behavior

Working cluster

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
