### ISSUE TITLE
[BUG] role not working as expected in OpenSearch Dashboards

### ISSUE THREAD

**Issue by atalakey4work** [opensearch-project/OpenSearch#18464]
### Describe the bug

I am trying to setup role and role binding in such a way that users have access to documents from specific Indices without using DLS.

I have the following setup in an OpenSearch cluster:

- Indices:
    - k8s-production-2025
    - k8s-preprod-2025

- index pattern:
    - k8s-*

- role:

```
    k8s-production:
      reserved: true
      hidden: false
      cluster_permissions:
        - cluster_composite_ops_ro
      index_permissions:
      - index_patterns:
        - "k8s-production-*"
        allowed_actions:
        - read
      tenant_permissions:
      - tenant_patterns:
        - k8s-production
        allowed_actions:
        - "kibana_all_read"
```

- role mapping:

```
    k8s-production:
      reserved: true
      hidden: false
      users:
      - test-user
```

Querying via OpenSearch API works as expected. On the other hand, in OpenSearch Dashboards, when I visit the "Discover" page using the "test-user" and select the "k8s-*" index pattern no logs are displayed and I get the following error:

```
Error
    at fetch_Fetch.fetchResponse (https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:412479)
    at async interceptResponse (https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:407289)
    at async https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:410181
```

When I update the role's index_patterns values to "k8s-*" everything works but i see documents from both indices.

I cannot use DLS because it applies least privilege access which makes it hard to predict user access.

### Related component

Search

### To Reproduce

1. Create the two indices
2. Create a user, role and role mapping

### Expected behavior

index_patterns in role should map to index name rather than the index pattern defined in Dashboards.
