### ISSUE TITLE
[Feature/extensions] Add framework support to read extensions.yml

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#3084]
Coming from: https://github.com/opensearch-project/OpenSearch/issues/1972
We now have the design of `extensions.yml` and would like to discover these extensions within the extensions framework. 

Code Pointer:
https://github.com/opensearch-project/OpenSearch/blob/feature/extensions/server/src/main/java/org/opensearch/plugins/PluginsOrchestrator.java#L83

- [ ] Add support to read extensions
- [ ] Add unit tests

extensions.yml:
```
extensions:
    - name: firstExtension
      ephemeralId: 'uniqueid'
      hostName: 'myIndependentPluginHost'
      hostAddress: '127.0.0.0'
      port: '9301'
      version: '2.0.0'
   - name: secondExtension
...
```
