### ISSUE TITLE
[BUG] indexCreatedVersionMajor is in the future: 9 Docker version latest

### ISSUE THREAD

**Issue by FrBillyD** [opensearch-project/OpenSearch#3222]
**Describe the bug**
My Docker OpenSearch node is unavailable since last release upgrade. The error is "indexCreatedVersionMajor is in the future: 9".

**To Reproduce**
I don't know. Just use docker-compose pull && docker-compose up -d

**Expected behavior**
My Node1 is unavailable.

**Plugins**
opensearch-security
opensearch-dashboards

**Host/Environment (please complete the following information):**
 - OS: Debian & Docker
 - Version 11 and Docker version 20.10.15

**Additional context**

**docker-compose logs :**

```
Attaching to node1
node1    | Disabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
node1    | Enabling OpenSearch Security Plugin
node1    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
node1    | [2022-05-06T08:26:52,839][INFO ][o.o.n.Node               ] [node1] version[1.3.2], pid[10], build[tar/6febcf7b53ff189de767e460e905e9e5aeecc8cb/2022-05-04T03:58:48.328641Z], OS[Linux/4.19.0-20-amd64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/11.0.15/11.0.15+10]
node1    | [2022-05-06T08:26:52,844][INFO ][o.o.n.Node               ] [node1] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]
node1    | [2022-05-06T08:26:52,844][INFO ][o.o.n.Node               ] [node1] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/opensearch-217437326822116702, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy, -Dopensearch.cgroups.hierarchy.override=/, -Xms512m, -Xmx6144m, -XX:MaxDirectMemorySize=3221225472, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
node1    | [2022-05-06T08:26:54,050][WARN ][stderr                   ] [node1] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
node1    | [2022-05-06T08:26:54,050][WARN ][stderr                   ] [node1] SLF4J: Defaulting to no-operation (NOP) logger implementation
node1    | [2022-05-06T08:26:54,050][WARN ][stderr                   ] [node1] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
node1    | [2022-05-06T08:26:54,067][INFO ][o.o.s.s.t.SSLConfig      ] [node1] SSL dual mode is disabled
node1    | [2022-05-06T08:26:54,067][INFO ][o.o.s.OpenSearchSecurityPlugin] [node1] OpenSearch Config path is /usr/share/opensearch/config
node1    | [2022-05-06T08:26:54,364][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] JVM supports TLSv1.3
node1    | [2022-05-06T08:26:54,368][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] Config directory is /usr/share/opensearch/config/, from there the key- and truststore files are resolved relatively
node1    | [2022-05-06T08:26:54,589][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] TLS Transport Client Provider : JDK
node1    | [2022-05-06T08:26:54,589][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] TLS Transport Server Provider : JDK
node1    | [2022-05-06T08:26:54,589][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] TLS HTTP Provider             : JDK
node1    | [2022-05-06T08:26:54,589][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2]
node1    | [2022-05-06T08:26:54,590][INFO ][o.o.s.s.DefaultSecurityKeyStore] [node1] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2]
node1    | [2022-05-06T08:26:54,815][INFO ][o.o.s.OpenSearchSecurityPlugin] [node1] Clustername: odfe-cluster
node1    | [2022-05-06T08:26:54,818][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] Directory /usr/share/opensearch/config has insecure file permissions (should be 0700)
node1    | [2022-05-06T08:26:54,818][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] Directory /usr/share/opensearch/config/jvm.options.d has insecure file permissions (should be 0700)
node1    | [2022-05-06T08:26:54,818][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] Directory /usr/share/opensearch/config/opensearch-notebooks has insecure file permissions (should be 0700)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/opensearch-notebooks/notebooks.yml has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/opensearch.keystore has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/chain.pem has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/opensearch.yml has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/log4j2.properties has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,819][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] Directory /usr/share/opensearch/config/opensearch-reports-scheduler has insecure file permissions (should be 0700)
node1    | [2022-05-06T08:26:54,820][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/opensearch-reports-scheduler/reports-scheduler.yml has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,820][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/cert.pem has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,820][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/elastic.yml.bak has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,820][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/jvm.options has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:54,820][WARN ][o.o.s.OpenSearchSecurityPlugin] [node1] File /usr/share/opensearch/config/privkey.pem has insecure file permissions (should be 0600)
node1    | [2022-05-06T08:26:55,347][INFO ][o.o.p.c.PluginSettings   ] [node1] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1, httpsEnabled: false, cleanup-metrics-db-files: true, batch-metrics-retention-period-minutes: 7, rpc-port: 9650, webservice-port 9600
node1    | [2022-05-06T08:26:55,783][INFO ][o.o.i.r.ReindexPlugin    ] [node1] ReindexPlugin reloadSPI called
node1    | [2022-05-06T08:26:55,784][INFO ][o.o.i.r.ReindexPlugin    ] [node1] Unable to find any implementation for RemoteReindexExtension
node1    | [2022-05-06T08:26:55,805][INFO ][o.o.j.JobSchedulerPlugin ] [node1] Loaded scheduler extension: opendistro_anomaly_detector, index: .opendistro-anomaly-detector-jobs
node1    | [2022-05-06T08:26:55,845][INFO ][o.o.j.JobSchedulerPlugin ] [node1] Loaded scheduler extension: reports-scheduler, index: .opendistro-reports-definitions
node1    | [2022-05-06T08:26:55,846][INFO ][o.o.j.JobSchedulerPlugin ] [node1] Loaded scheduler extension: opendistro-index-management, index: .opendistro-ism-config
node1    | [2022-05-06T08:26:55,848][INFO ][o.o.p.PluginsService     ] [node1] loaded module [aggs-matrix-stats]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [analysis-common]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [geo]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [ingest-common]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [ingest-geoip]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [ingest-user-agent]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [lang-expression]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [lang-mustache]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [lang-painless]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [mapper-extras]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [opensearch-dashboards]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [parent-join]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [percolator]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [rank-eval]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [reindex]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [repository-url]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded module [transport-netty4]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-alerting]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-anomaly-detection]
node1    | [2022-05-06T08:26:55,849][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-asynchronous-search]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-cross-cluster-replication]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-index-management]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-job-scheduler]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-knn]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-ml]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-observability]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-performance-analyzer]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-reports-scheduler]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-security]
node1    | [2022-05-06T08:26:55,850][INFO ][o.o.p.PluginsService     ] [node1] loaded plugin [opensearch-sql]
node1    | [2022-05-06T08:26:55,860][INFO ][o.o.s.OpenSearchSecurityPlugin] [node1] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in opensearch.yml
node1    | [2022-05-06T08:26:55,868][DEPRECATION][o.o.d.c.s.Settings       ] [node1] [node.max_local_storage_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
node1    | [2022-05-06T08:26:55,874][INFO ][o.o.e.NodeEnvironment    ] [node1] using [1] data paths, mounts [[/mount/backups (/dev/mapper/VG00-LV01)]], net usable_space [125.5gb], net total_space [152.2gb], types [ext4]
node1    | [2022-05-06T08:26:55,874][INFO ][o.o.e.NodeEnvironment    ] [node1] heap size [5.9gb], compressed ordinary object pointers [true]
node1    | [2022-05-06T08:26:58,415][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node1] uncaught exception in thread [main]
node1    | org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9
node1    |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.2.jar:1.3.2]
node1    | Caused by: java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9
node1    |         at org.apache.lucene.index.SegmentInfos.<init>(SegmentInfos.java:169) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:327) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |         at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.2.jar:1.3.2]
node1    |         ... 6 more
node1    |         Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (b5ccfd9d). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/mount/backups/nodes/0/_state/segments_j1y")))
node1    |                 at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:466) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:434) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64) ~[lucene-core-8.10.1.jar:8.10.1 2f24e6a49d48a032df1f12e146612f59141727a9 - mayyasharipova - 2021-10-12 15:13:05]
node1    |                 at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.2.jar:1.3.2]
node1    |                 at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.2.jar:1.3.2]
node1    | uncaught exception in thread [main]
node1    | java.lang.IllegalArgumentException: indexCreatedVersionMajor is in the future: 9
node1    |         at org.apache.lucene.index.SegmentInfos.<init>(SegmentInfos.java:169)
node1    |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:327)
node1    |         at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
node1    |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64)
node1    |         at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61)
node1    |         at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720)
node1    |         at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84)
node1    |         at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64)
node1    |         at org.opensearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:302)
node1    |         at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:441)
node1    |         at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:357)
node1    |         at org.opensearch.node.Node.<init>(Node.java:414)
node1    |         at org.opensearch.node.Node.<init>(Node.java:319)
node1    |         at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
node1    |         at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
node1    |         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
node1    |         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
node1    |         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
node1    |         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
node1    |         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
node1    |         at org.opensearch.cli.Command.main(Command.java:101)
node1    |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
node1    |         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
node1    | For complete error details, refer to the log at /usr/share/opensearch/logs/odfe-cluster.log
```

**docker-compose.yml file :**

```
version: '3'

services:
  node1:
    image: opensearchproject/opensearch:latest
    container_name: node1
    hostname: node1.mydomain
    restart: always
    environment:
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - cluster.name=cluster
      - node.name=node1.mydomain
      - discovery.seed_hosts=node1.mydomain
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx6144m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0 # required if not using the demo security configuration
      - SERVER_SSL_CERTIFICATE=/usr/share/opensearch/config/cert.pem
      - path.data=/mount/backups
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - /home/opensearch/node1/data:/usr/share/opensearch/data
      - /home/opensearch/node1/logs:/usr/share/opensearch/logs
      - /home/opensearch/node1/config:/usr/share/opensearch/config
      - /etc/ssl/priv/chain.pem:/usr/share/opensearch/config/chain.pem
      - /etc/ssl/priv/cert.pem:/usr/share/opensearch/config/cert.pem
      - /etc/ssl/priv/privkey.pem:/usr/share/opensearch/config/privkey.pem
      - /home/opensearch/node1/plugins/securityconfig:/usr/share/opensearch/plugins/opensearch-security/securityconfig
      - /home/opensearch/node1/backups:/mount/backups
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      net:
        aliases:
          - node1
          - node1.mydomain

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    hostname: kibana.mydomain
    restart: always
    environment:
      JAVA_HOME: /usr/share/opensearch/jdk
      OPENSEARCH_HOSTS: '["https://node1:9200"]'
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/opensearch-dashboards/config/privkey.pem
      SERVER_SSL_CERTIFICATE: /usr/share/opensearch-dashboards/config/cert.pem
    volumes:
      - /home/opensearch/dashboards/config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - /etc/ssl/priv/chain.pem:/usr/share/opensearch-dashboards/config/chain.pem
      - /etc/ssl/priv/cert.pem:/usr/share/opensearch-dashboards/config/cert.pem
      - /etc/ssl/priv/privkey.pem:/usr/share/opensearch-dashboards/config/privkey.pem
    ports:
      - "5601:5601"
    networks:
      net:
        aliases:
          - kibana
          - kibana.mydomain
    depends_on:
      - node1

  logstash:
    image: logstash:7.11.1
    container_name: logstash
    hostname: logstash.mydomain
    restart: always
    environment:
      NODE_NAME: logstash.mydomain
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      - /home/opensearch/logstash/config:/usr/share/logstash/pipeline
      - /home/opensearch/logstash/certs:/usr/share/certs
      - /etc/ssl/priv/chain.pem:/usr/share/logstash/config/chain.pem
      - /etc/ssl/priv/cert.pem:/usr/share/logstash/config/cert.pem
      - /etc/ssl/priv/privkey.pem:/usr/share/logstash/config/privkey.pem
    ports:
      - "9401:9401"
      - "9402:9402"
      - "9403:9403"
      - "9404:9404"
      - "5044:5044"
      - "5045:5045"
    networks:
      net:
        aliases:
          - logstash
          - logstash.mydomain
    depends_on:
      - node1

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=mydomain
      - EXTRA_DOMAINS=*.mydomain
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=contact@mydomain
      - STAGING=false
      - ONLY_SUBDOMAINS=false
    volumes:
      - /home/opensearch/swag:/config
    networks:
      - net
    ports:
      - "443:443"
    links:
      - dashboards
    depends_on:
      - dashboards
    restart: always

networks:
  net:
```
