### ISSUE TITLE
[BUG] processors:set.copy_from: isn't understood breaking pipelines

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/OpenSearch#4672]
**Describe the bug**
With Elasticsearch 7.11 (i.e. the version immediately after OpenSearch fork), "copy_from" option for the "set" processor has been introduced, here - https://www.elastic.co/guide/en/elasticsearch/reference/7.11/set-processor.html

this breaks a lot of pipelines, registering pipelines will throw the following error:

```
Exiting: 1 error: error loading pipeline for fileset system/auth: couldn't load pipeline: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"parse_exception","reason":"[value] required property is missing","processor_type":"set","property_name":"value"}],"type":"parse_exception","reason":"[value] required property is missing","processor_type":"set","property_name":"value"},"status":400}. Response body: {"error":{"root_cause":[{"type":"parse_exception","reason":"[value] required property is missing","processor_type":"set","property_name":"value"}],"type":"parse_exception","reason":"[value] required property is missing","processor_type":"set","property_name":"value"},"status":400}
```

a workaround is available and requires to change

```
processors:
  - set:
      field: myfiled
      copy_from: myvalue
```

to 

```
processors:
- set:
    field: myfiled
    value: '{{myvalue}}'
```
