### ISSUE TITLE
Migrating to OpenSearch but query slower than expected

### ISSUE THREAD

**Issue by mxptrs-px** [opensearch-project/OpenSearch#4694]
Hi Guys,

We consider to move to OpenSearch as search cluster for our solution. The first test showed that performance for our search queries seems to be much slower than in our ElasticSearch setup.

We tested this in a simple scenario, which is described below. The result times of the queries are as follow (when executed 1000x)

```
ELASTIC-7.11.2   : Took: 27696 ms,   # Results: 483340
OPENSEARCH-1.3.4 : Took: 46525 ms,   # Results: 483340
OPENSEARCH-2.3.0 : Took: 43378 ms,   # Results: 483340
```

Test scenario:

- single node search engine (in docker, 4gb memory, no-auth, other settings out-of-the-box)
- simple schema with Name (firstname + lastname) with ngram(1,2) analyzer (eg. "Padron, Briana")
- index with 1mio. documents
- query matching names base on ngram (with min. 75% match)

What can be the reason for slower performance of the queries?

Query:
```
{
    "size": 100,
    "query": {
        "match": {
            "Name.onetwogram": {
                "query": "Padron, Briana",
                "minimum_should_match": "75%"
            }
        }
    }
}
```

Schema:
```
dynamic: false
properties:
  Name:
    type: keyword
    fields:
      onetwogram: { type: text, analyzer: onetwogram_analyzer}
```

Analyzer:
```
index:
  refresh_interval: -1
analysis:
  tokenizer:
    onetwogram_tokenizer:
      type: ngram
      min_gram: 1
      max_gram: 2
  analyzer:
    onetwogram_analyzer:
      tokenizer: onetwogram_tokenizer
```

**Comment by Bukhtawar** [comment]
Also it might be good to see how the numbers stacked up for OPENSEARCH-1.0

**Comment by mxptrs-px** [comment]
> Next, is this something about these particular queries (try with a much simpler query to get a baseline)?

> Also it might be good to see how the numbers stacked up for OPENSEARCH-1.0

I added a basic type to my mapping and reran the tests (on a different system today, so the absolute times are higher, but the relative differences are still there).

<details>
  <summary>settings.yaml</summary>

  ```yml
  dynamic: false
  properties:
    Name:
      type: keyword
      fields:
        onetwogram: { type: text, analyzer: onetwogram_analyzer }
        basic: { type: text }
  ```
</details>

<details>
  <summary>Query is nearly the same</summary>

  ```json
  {
    "size": 100,
    "query": {
      "match": {
        "Name.basic": {
          "query": "Padron, Briana",
          "minimum_should_match": "75%"
        }
      }
    }
  }
  ```
</details>

```
ELASTIC-7.11.2:
 >> onetwogram: Took:  79393 ms
 >> basic:      Took:   2554 ms

OPENSEARCH-1.0.0:
 >> onetwogram: Took: 645492 ms
 >> basic:      Took:   2527 ms

OPENSEARCH-1.1.0:
 >> onetwogram: Took: 108886 ms
 >> basic:      Took:   2411 ms

OPENSEARCH-1.3.4:
 >> onetwogram: Took: 101952 ms
 >> basic:      Took:   2878 ms

OPENSEARCH-2.3.0:
 >> onetwogram: Took: 103630 ms
 >> basic:      Took:   2887 ms
```

Opensearch 1.0.0 is pretty slow for the ngram analyzer. I repeated the test a few times and it was always nearly the same results.
