### ISSUE TITLE
[Proposal] Create Upgrade Simulation Framework

### ISSUE THREAD

**Issue by chelma** [opensearch-project/OpenSearch#5167]

**Comment by dblock** [comment]
@chelma I suggest bringing some of this discussion in some presentation form to the community meeting, too!

**Comment by chelma** [comment]
@dblock Great idea, will do!

**Comment by gregschohn** [comment]
I like the usage of docker, but it will slightly narrow the scope of what kinds of tests you'd like to run.  I'm thinking of performance tests - confirming that there are no regressions in performance for a given workload across a similarly situated cluster.  Another one, would be to test on windows clusters, once OpenSearch is available for > 1 release.

Those can be future concerns, but it would be nice to not over constrain the design now.

**Comment by dblock** [comment]
- I think simulation framework doesn't give this proposal justice. This sounds like it's an "upgrade testing framework".
- I would take the goal to supersede and delete the bwc framework code in OpenSearch.
- I'd like to get a tool that can analyze a production cluster and generate an upgrade configuration that I can then run through the migration/upgrade framework to see whether that would work. Then replicate my cluster with full cluster replication and run the tools against my production data copy (this time it will test search queries), then I want to do the real upgrade and failover.
- I'd like to be able to leverage GitHub for collaboration/knowledge base/contribution regressions/configurations/etc.

**Comment by peternied** [comment]
Great proposal thanks for putting this out there!

* I don't think this tool should live inside of OpenSearch - I think it should be part of its own repository.  The way upgrade testing is conducted shouldn't be tightly coupled with the version of OpenSearch.

* Include a mock of the input(s) to the tool, it would help clarify the range of supported scenarios.

We've added a GitHub Action [1] that orchestrates the BWC framework for ad-hoc version to version tests, with the following input.  If we could cleanly use this tool to replace the under-the-covers components of this GitHub Action our team would gladly adopt.

```
jobs:
  last-supported-major-to-current:
    ...
    - uses: ./.github/actions/run-bwc-suite
      with:
        plugin-previous-branch: "1.3"
        plugin-next-branch: "2.x"
        report-artifact-name: BWC-Last-Supported-Major

  current-to-next-unreleased-major:
    ...
    - uses: ./.github/actions/run-bwc-suite
      with:
        plugin-previous-branch: "2.x"
        plugin-next-branch: "main"
        report-artifact-name: BWC-Next-Major
```

[1] https://github.com/opensearch-project/security/pull/2253


* Cluster Admin uses cases are framed around a knowledgeable admin.  Depending on how we want this tool to be used it might be worthwhile to invest in lowering the barrier to extracting value from the tool.  Automatically discovering the current cluster configuration is a great way to add instant value.  Helping the cluster admin know what is tested or what could be tested might also be of value.

* This tool is framed around relatively local testing (containers), supporting remote/cloud managed cluster as sources or destinations would be useful for many more migration scenarios.

* Might want to describe the capabilities of tests that are executed, seems like the tool will need some level of test harness / tracking.

* Checkout https://github.com/opensearch-project/opensearch-benchmark while built for performance benchmarking on a single cluster with cluster standup / interaction, maybe it can be extended or aspects reused.

* Orthogonally to the functionality proposed - I'd recommend the tool be written in a strongly typed language.
