### ISSUE TITLE
[BUG] NotSslRecordException: not an SSL/TLS record - When using docker

### ISSUE THREAD

**Issue by RyanNoelk** [opensearch-project/OpenSearch#5836]
**Describe the bug**
I get the following error when trying to query data from opensearch via docker compose:
```io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record```

**To Reproduce**
Using the following docker compose file:
```
version: '3.9'
services:
  es:
    image: opensearchproject/opensearch:1.0.1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200
  kibana:
    image: opensearchproject/opensearch-dashboards:1.0.1 
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://es:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
```

The code I use to connect to and query is the same as I am using for elasticsearch 7.10. Everything works as expected in elasticsearch but not in opensearch. I've also tried a few different versions on opensearch and all of them yield the same result.

**Expected behavior**
I would expect this to work out of the box, just like with elasticsearch 7.10.
