### ISSUE TITLE
[BUG] Custom config files cannot take effect

### ISSUE THREAD

**Issue by Alendill** [opensearch-project/OpenSearch#6454]
**Describe the bug**
We are trying to manage authentication and authorization via config.yml as Document says.
But we found it never take effect. This caused us to be unable to pass OIDC authentication and login(Always receive {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"})
Our opensearch is deployed via Helm-chart in GKE environment, and manage by ArgoCD.
And we also checked the configuration in the values.
And the "config.yml" under the default config path("/usr/share/opensearch/config/opnsearch-security") in each pod can also see our own configuration content.

Versions:
  Opensearch: 2.5.0
  Openserach_Helm-chart: 2.10.0
  Opensearch-dashboard: 2.5.0
  Opensearch-dashboard_Helm-chart: 2.8.0

**To Reproduce**
1. Deploy opensearch via helm-chart.
2. Use "values.yml" as a template to add custom content, be like:
```
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/config/opnsearch-security"
  config:
    securityConfigSecret: ""
    dataComplete: true
    data:
      config.yml: |
      ... some our own config(e.g. There is no "openid_auth_domain" in default value, we added it. And "jwt_auth_domain.http_enabled" default is false, we change false to true)
```
3. Sync application in ArgoCD.
4. When each pod online, logon opensearch-dashboard page via admin, and into "Security" -> "Authentication"
5. There is no our own config effect, no "openid_auth_domain" displayed on "Authentication sequences" and "jwt_auth_domain.http_enabled" still is false.
6. We tried comment all of auth domain except "basic_internal_auth_domain"

**Expected behavior**
Make custom config take effect, or else find why it does not take effect.

**Plugins**
All default plugins.

**Screenshots**
Sorry for these camera shoots, because of company policy, me cannot post screenshots directly here :(
1. Part of values.
![0aa0b41e994dd13ac72ab61fab20e5c](https://user-images.githubusercontent.com/40451613/220814834-73118bd0-fcf6-4da1-92b2-36c01fae27ef.jpg)
![ab217c6b93c25ecd4729d713669f844](https://user-images.githubusercontent.com/40451613/220814897-2f1e261f-7ff5-4650-bd8d-b767cf1a3e26.jpg)
![4f5ace97acd071fe5e575a7e29abb31](https://user-images.githubusercontent.com/40451613/220814896-bd40fa41-d15b-4e64-8d45-167837375ff7.jpg)

2. Opensearch-dashboard "Security" -> "Authentication" page.
![d641978a969f211fdfd131411bb88e0](https://user-images.githubusercontent.com/40451613/220814895-75aff451-e888-461b-a9bb-a69279c894e9.jpg)

3. "config.yml" in pod.
![5e4155cfe1bd878c618acb43d5062ed](https://user-images.githubusercontent.com/40451613/220814959-26faf078-3383-4a17-a00c-682d4c649bf8.jpg)

**Host/Environment (please complete the following information):**
 - OS: Google Kubernetes Engine(We do not known which specific Linux version is)

**Additional context**
If you need anything else please told me.
