### ISSUE TITLE
[BUG] no permissions for [indices:data/read/search] when tenant is set to 'global'

### ISSUE THREAD

**Issue by laszloszurok** [opensearch-project/OpenSearch#6803]
I am trying to create a security role which lets a user view dashboards in the global tenant. I defined the following role in roles.yaml:
```
  dashboards_role:
    cluster_permissions: []
    index_permissions:
      - index_patterns:
          - '*'
        allowed_actions:
          - '*'
    tenant_permissions:
      - tenant_patterns:
          - 'global'
        allowed_actions:
          - '*'
```
When I navigate to the Dashboards menupoint with a user with the above role I can only see a blank screen:
![2023-03-23 10_44_50-VirtualBoxVM](https://user-images.githubusercontent.com/48314396/227164916-f32402bc-7061-4bdb-9efc-097e85cea745.png)

In the opensearch dashboards logs I see the following line:
`["error","opensearch","data"],"pid":1,"message":"[security_exception]: no permissions for [indices:data/read/search] and User [name=dev1, backend_roles=[my_role], requestedTenant=]`

If I change the tenant_patterns to '*' it works correctly and I do not see the log line above.
```
    tenant_permissions:
      - tenant_patterns:
          - '*'
        allowed_actions:
          - '*'
```
OpenSearch version: 2.4
