### ISSUE TITLE
[BUG] [Searchable Snapshot] Snapshot of remote indices can cause errors or search node to "lock up"

### ISSUE THREAD

**Issue by dgilling** [opensearch-project/OpenSearch#7179]
**Describe the bug**

**To Reproduce**
1. Trigger a snapshot that includes remote indices as part of the "indices" list. 
2. As soon as snapshot starts, errors are printed in logs of nodes with the "search" role: `Unknown blob in the repository: index-ZhVRxGZe8PNVXS4PIrO_og`
3. Shortly after snapshot starts (<30 mins into snapshot process) the `search` nodes stop responding to cluster commands like the stats API even though nodes are still part of cluster and could still execute other commands. i.e. `localhost:9200/_nodes/c85655afee28/stats` would respond with 

```
{"_nodes":{"total":1,"successful":0,"failed":1,"failures":[{"type":"failed_node_exception","reason":"Failed node [e2Lm1TxM12R4eWAcnmihGO]","node_id":"e2Lm1TxM12R4eWAcnmihGO","caused_by":{"type":"receive_timeout_transport_exception","reason":"[c85655afee28][10.10.0.2:9300][cluster:monitor/nodes/stats[n]] request_id [63271493] timed out after [30023ms]"}}]},"cluster_name":"elasticsearch-test-script-patch","nodes":{}}
```

Similarly, other commands like `/_cat/tasks` would hang. 
4. A simple restart of `search` nodes will remedy the lock up. 

While not positive the snapshot job is causing the lockup, it did occur on 3 separate occurrences right after starting a snapshot so seems like strong correlation. Was seen during testing of #6996 

**Expected behavior**
Snapshotting remote indices shouldn't cause the node to print errors or fail to respond to cluster cmds. 

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

Build based on 2.x snapshot. manifest.yml below:

```
schema-version: '1.1'
build:
  name: OpenSearch
  version: 2.7.0
  platform: linux
  architecture: x64
  distribution: tar
  location: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7686/linux/x64/tar/dist/opensearch/opensearch-2.7.0-linux-x64.tar.gz
  id: '7686'
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2.x
    commit_id: a32eb144862afcef5229df6ff8d2475b83bd6000
    location: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7686/linux/x64/tar/builds/opensearch/dist/opensearch-min-2.7.0-linux-x64.tar.gz
```

**Additional context**
