### ISSUE TITLE
[BUG] Cors Not Working.

### ISSUE THREAD

**Issue by zalseryani** [opensearch-project/OpenSearch#7288]
# Issue
- defining cors origin in ```opensearch.yml``` and verifying that its loaded into the engine, but I am able to curl from another pod inside kubernetes cluster and after port-forwarding the pod port 9200 to my machine on same port where the engine should not respond to the request since I am using hitting from a domain or IP that is not defined in cors origin. 

# opensearch.yml configuration 
```yaml
opensearch.yml: |
    cluster.name: opensearch-cluster

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
    # Implicitly done if ".singleNode" is set to "true".
    # discovery.type: single-node

    http:
      host: 0.0.0.0
      port: 9200
      cors:
        allow-origin: "https://opensearch.devops-dev-ing.x.x"
        enabled: "true"
        allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        allow-credentials: true
    # Start OpenSearch Security Demo Configuration
    # WARNING: revise all the lines below before you go into production
    plugins:
      security:
        ssl:
          transport:
            pemcert_filepath: esnode.pem
            pemkey_filepath: esnode-key.pem
            pemtrustedcas_filepath: root-ca.pem
            enforce_hostname_verification: false
          http:
            enabled: true
            pemcert_filepath: esnode.pem
            pemkey_filepath: esnode-key.pem
            pemtrustedcas_filepath: root-ca.pem
        allow_unsafe_democertificates: true
        allow_default_init_securityindex: true
        authcz:
          admin_dn:
            - CN=kirk,OU=client,O=client,L=test,C=de
        audit.type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: true
          indices:
            [
              ".opendistro-alerting-config",
              ".opendistro-alerting-alert*",
              ".opendistro-anomaly-results*",
              ".opendistro-anomaly-detector*",
              ".opendistro-anomaly-checkpoints",
              ".opendistro-anomaly-detection-state",
              ".opendistro-reports-*",
              ".opendistro-notifications-*",
              ".opendistro-notebooks",
              ".opendistro-asynchronous-search-response*",
            ]
    ######## End OpenSearch Security Demo Configuration ########
```

![image](https://user-images.githubusercontent.com/49269877/233998855-c05691c2-a199-4b09-9b86-08a16929b6b5.png)

# Port-Forwarding the pod to my local machine. 

![image](https://user-images.githubusercontent.com/49269877/233999552-a80ec723-57ca-426b-b9eb-69e3099ecf51.png)

- I am still able to access it using localhost
![image](https://user-images.githubusercontent.com/49269877/233999749-63beb020-34c9-4dd5-947a-08d6c3d7a578.png)

- also still able to rearch the engine from another pod in another namespace. 
![image](https://user-images.githubusercontent.com/49269877/234000774-6e63dfc1-07bb-475e-b067-9eae9f98e966.png)

# Opensearch Release Information:
- AppVersion: ```2.6.0```
- Chart Version: ```2.11.3```

Kindly advise if I am doing something wrong,
I tried to follow the documentation of opensearch to add the cors configs with '-' but it did not work and statefulsets failed to startup 

Thank you.
