### ISSUE TITLE
Mapping `char_filter` for `'# => _hashsign_'` not working from version 2.4.0 

### ISSUE THREAD

**Issue by nathanmyles** [opensearch-project/OpenSearch#7308]
**Describe the bug**
We have the analyzer defined below:
```python
from elasticsearch_dsl import analyzer, char_filter


STD_WITH_SPECIAL_CHARS: Final = analyzer(
    'std_with_special_chars',
    type='custom',
    tokenizer='standard',
    filter=['lowercase'],
    char_filter=char_filter(
        'social_char_filter',
        type='mapping',
        mappings=[
            '# => _hashsign_',
            '@ => _atsign_'
        ],
    ),
)
```

On version 2.3.0 and below, this works as expected:
```python
STD_WITH_SPECIAL_CHARS.simulate('test #test @test', using=es_connection)
```
returns:
```python
{
    'tokens': [
        {
            'token': 'test', 
            'start_offset': 0, 
            'end_offset': 4, 
            'type': '<ALPHANUM>', 
            'position': 0
        }, 
        {
            'token': '_hashsign_test', 
            'start_offset': 5, 
            'end_offset': 10, 
            'type': '<ALPHANUM>', 
            'position': 1
        }, 
        {
            'token': '_atsign_test', 
            'start_offset': 11, 
            'end_offset': 16, 
            'type': '<ALPHANUM>', 
            'position': 2
        }
    ]
}
```
On version 2.4.0 and above, it returns:
```python
{
    'tokens': [
        {
            'end_offset': 4,
            'position': 0,
            'start_offset': 0,
            'token': 'test',
            'type': '<ALPHANUM>'
        },
        {
            'end_offset': 10,
            'position': 1,
            'start_offset': 6,
            'token': 'test',
            'type': '<ALPHANUM>'
        },
        {
            'end_offset': 16,
            'position': 2,
            'start_offset': 11,
            'token': '_atsign_test',
            'type': '<ALPHANUM>'
        }
    ]
}
```

For some reason the `#` is not converted to `_hashsign_`. Our `@` character mapping still works so there must be something specific to `#` happening here?

**To Reproduce**
1. Create an analyzer with a mapping char_filter, mappings `'# => _hashsign_'`
2. analyzer text with a hashtag
3. See output is not converted

**Expected behavior**
Analyzed tokens with `#` to have them converted to `_hashsign_`

**Plugins**
N/A

**Host/Environment (please complete the following information):**
 - OS: N/A
 - Version 2.4.0

**Comment by dblock** [comment]
Want to try to turn it into a REST YAML unit test?

**Comment by nathanmyles** [comment]
Hmm, I'm not familiar with the REST YAML unit tests. Any pointers? I'm using the OpenSearch docker containers to run this code so haven't built the project.

**Comment by nathanmyles** [comment]
Haven't run this but something like this?

```yaml
- do:
      indices.analyze:
        body:
          text: 'text #text @text'
          tokenizer: standard
          filter:
            - type: lowercase
          char_filter:
            - type: mapping
              mappings:
                - '# => _hashsign_'
                - '@ => _atsign_'

  - length: { tokens: 3 }
  - match:  { tokens.0.token: test }
  - match:  { tokens.1.token: _hashsign_test }
  - match:  { tokens.2.token: _atsign_test }
```

**Comment by dblock** [comment]
Yep. Check out https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer for dev docs on how to write these. And please feel free to improve that documentation if something is not clear!

**Comment by nathanmyles** [comment]
I'm having issues getting the REST YAML unit tests working with the `char_filter`.

If I run the test:
```yaml
"Character filter in request":
    - do:
        indices.analyze:
          body:
            text: 'test #test @test'
            tokenizer: standard
            filter:
              - lowercase

    - length: { tokens: 3 }
    - match: { tokens.0.token: test }
    - match: { tokens.1.token: test }
    - match: { tokens.2.token: test }
```

It passes, but if I add in the `char_filter` like this:
```yaml
"Character filter in request":
    - do:
        indices.analyze:
          body:
            text: 'test #test @test'
            tokenizer: standard
            filter:
              - lowercase
            char_filter:
              - type: mapping
                mappings:
                  - '# => _hashsign_'
                  - '@ => _atsign_'

    - length: { tokens: 3 }
    - match: { tokens.0.token: test }
    - match: { tokens.1.token: test }
    - match: { tokens.2.token: test }
```

I get an error: `failed to find global char_filter under [mapping]`

If I run this rest request against our cluster, it works (but returns the bugged response outlined above since it's on version 2.5.0)

```
GET _analyze
{
    "tokenizer" : "standard",
    "filter": ["lowercase"],
    "char_filter": [
      {
        "type": "mapping",
        "mappings": [
          "# => _hashsign_",
          "@ => _atsign_" 
        ]
      }
    ], 
    "text" : "test #test @test"
}
```
```
{
  "tokens": [
    {
      "token": "test",
      "start_offset": 0,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "test",
      "start_offset": 6,
      "end_offset": 10,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "_atsign_test",
      "start_offset": 11,
      "end_offset": 16,
      "type": "<ALPHANUM>",
      "position": 2
    }
  ]
}
```

Am I missing something about using `char_filter` in these tests?
