### ISSUE TITLE
[BUG] Cannot update custom fields via /_update_by_query

### ISSUE THREAD

**Issue by flkhndlr** [opensearch-project/OpenSearch#8079]
**Describe the bug**
After creating a custom field via the _update_by_query endpoint we tried to update the value of the field with yet another call to the _update_by_query endpoint. While this requests returns the expected response for a successfull update, the value of that field remains unchanged.

**To Reproduce**
1. Create a custom field on your document via a query
```
curl --location --request PUT 'localhost:9200/logmon_test/_doc/6' \
--header 'Content-Type: application/json' \
--data '{
  "tags": [
    "opster",
    "OpenSearch"
  ],
  "test": 0,
  "date": "01-01-2020"
}'
```
2. Try to update a document in which you have created a custom field
```
curl --location 'localhost:9200/<index_name>/_update_by_query' \
--header 'Content-Type: application/json' \
--data '{
  "query": {
    "term": {
      "test": 0
    }
  },
  "script" : {
    "source": "ctx._source.test += params.newValue",
    "lang": "painless",
    "params" : {
      "newValue" : 2
    }
  }
}'
```
3. Check the result either via <index_name>/_search
```
{
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "<index_name>",
                "_id": "6",
                "_score": 1.0,
                "_source": {
                    "date": "01-01-2020",
                    "test": 0,
                    "tags": [
                        "opster",
                        "OpenSearch"
                    ]
                }
            }
        ]
    }
}
```

**Expected behavior**

The Value of "test" should be 2 not 0.

**Plugins**
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-neural-search
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-security-analytics
opensearch-sql

**Host/Environment (please complete the following information):**
 -Docker Container 2.6.0 and 2.8.0

**Additional context**
- while the value of the field remains the same, the version increments
- it is possible to create and update fields if they share the name with a field outside of _src (e.g. _score; _type)
- we have waited multiple refresh periods and trigger them manually

**Comment by flkhndlr** [comment]
Thanks so much for the reply. Id love to try to write a YAML rest test, but I honest don't know how and where to integrate it correctly. Could you point me to where to start with it?

**Comment by dblock** [comment]
Check out https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-the-rest-layer. That doc could use some love too, but it will get you started!

**Comment by dblock** [comment]
Your original bug doesn't seem to have anything to do with pipelines, now I am confused :) I am thinking something along the lines of https://github.com/opensearch-project/OpenSearch/blob/bea26f97c66070581070764fe4790d2f0579c8e7/qa/smoke-test-ingest-with-all-dependencies/src/test/resources/rest-api-spec/test/ingest/30_update_by_query_with_ingest.yml#L4

**Comment by flkhndlr** [comment]
Oh i made a mistake. I pasted the wrong file.

The test i ment to send was this:

```
---
setup:
  - do:
      indices.create:
        index: test
        body:
          settings:
            index:
              refresh_interval: -1
              number_of_replicas: 0

  - do:
      ingest.put_pipeline:
        id: 1
        body: >
          {
            "description": "_description",
            "processors": [
              {
                "set" : {
                  "field": "testField",
                  "value": "new"
                }
              }
            ]
          }

  - do:
      indices.put_settings:
        index: test
        body:
          index.default_pipeline:  1

  - do:
      index:
        index:   test
        id:      1
        body:    { count: 0 }


---
"First test":
  - do:
      update_by_query:
        refresh: true
        index: test
        body:
          query:
            match:
              testField: new
          script:
            lang: painless
            source: ctx._source.testField = inwork

#  - match: {noops: 0}
#  - match: {updated: 1}

  - do:
      get:
        index:  test
        id:     1

  - match:  { _source.testField: inwork }

```

I'm so sorry for inconvenience. I hope this time it is more explanatory.
