### ISSUE TITLE
[Remote Store] Support repository registration during node bootstrap

### ISSUE THREAD

**Issue by psychbot** [opensearch-project/OpenSearch#8193]
**Is your feature request related to a problem? Please describe.**
Today we supports the registration of a repository via [Put API call](https://opensearch.org/docs/latest/api-reference/snapshots/create-repository/). But with remote backed storage we want all the indices to be remotely backed including system indices which essentially means that the repository registration has to be part of node bootstrap for system indices to be backed to remote store.

If the repository is not available during the bootstrap and the Opensearch cluster has the remote backed storage enabled will result in system indices being red.

**Describe the solution you'd like**
We would want to pass the repository information as part of yml file such that during the node bootstrap itself the repository gets registered.

Expected yml content
```
repositories: 
    my-fs-repository:
        type: "fs"
        location: "/mnt/snapshots"
    my-opensearch-repo:
        type: "s3"
        bucket: "bucket_name"
        region: "us-west-2"
```
