### ISSUE TITLE
[BUG] Tildes in map doesn't load in exported reports

### ISSUE THREAD

**Issue by secudna** [opensearch-project/OpenSearch#8833]
**Describe the bug**
Tildes in map doesn't load in exported reports
**To Reproduce**

```
version: '3'
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    expose:
      - "9200" # Expose port 5601 for web access to OpenSearch Dashboards
    image: opensearchproject/opensearch:2.8.0 # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1  # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1  # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - 'opensearch-net'

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
```

1. Go to the dashboard
2. Click on reporting
3. Report PDF (or png)
4. Check the report

<img width="1433" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/109231119/5d6c4298-494c-4cb6-a259-97c2c02c789f">
<img width="997" alt="image" src="https://github.com/opensearch-project/OpenSearch/assets/109231119/e8ade860-607b-4f5f-bfe3-0f28bd0dbd2b">
