### ISSUE TITLE
[BUG] GitHub Action workflows should not execute on other forks

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#9224]
**Describe the bug**

GitHub Actions meant to run on the OpenSearch repo are running on all forks.

**To Reproduce**
1. Fork the project (or sync an existing fork to `main`)
2. Wait long enough for scheduled actions to trigger
3. Check your email, or check your action history, e.g., https://github.com/dbwiddis/OpenSearch/actions?query=is%3Afailure
4. Observe multiple failed workflows on your fork

**Expected behavior**

No workflows executing on forks.

**Screenshots**

![Screenshot 2023-08-10 at 8 57 24 AM](https://github.com/opensearch-project/OpenSearch/assets/9291703/3af2db37-fee7-4367-bda8-3086c8021444)

**Additional context**

The ideal solution is to use the [if conditional](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) to limit the workflow run.  The link gives a specific example:
```yml
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
```

It is possible to configure forks to disable all workflows, to remove this annoyance, but all contributors who have forked OpenSearch should not have to do this.

![image](https://github.com/opensearch-project/OpenSearch/assets/9291703/11fae440-8140-4289-91ce-aaf74c6847bc)
