### ISSUE TITLE
Allow configuring the default behavior for 'number_of_replicas'

### ISSUE THREAD

**Issue by drewmiranda-gl** [opensearch-project/OpenSearch#9438]
**Is your feature request related to a problem? Please describe.**

This feature request is in search of solving a very common problem with single-node opensearch clusters. By default, opensearch will always try to set `number_of_replicas` to 1 when a new index is created. While this can be overridden by having whatever creates the index explicitly configure this, in some cases, opensearch automatically creates/generates indexes and doesn't allow the user any control over this.

What happens is that replica shards are created (because of the default `number_of_replicas: 1`) and this will cause the health of a single node cluster to always be yellow (instead of green).

While the resolution is 'easy', it requires the user to know the resolution exists and to also manually carry it out. They also cannot proactively prevent it and must wait for the index to appear before they can adjust:

```
curl -X PUT "http://127.0.0.1:9200/.opendistro-*/_settings" -H 'Content-Type: application/json' -d '{"index":{"number_of_replicas":0}}'
```

**Describe the solution you'd like**

1. either change the default of `number_of_replicas` to 0
2. OR allow this to be either a cluster configuration setting (that can be changed via the api) OR a cluster yml configuration setting

**Describe alternatives you've considered**

Alternatives listed above are manually observing this happening and applying the web request above to change `number_of_replicas` to 0. This is burdensome to the user though and many will not know what is happening, why, and how they should resolve it.

**Additional context**

See also https://github.com/opensearch-project/anomaly-detection/issues/847

**Comment by drewmiranda-gl** [comment]
Apologies if this is not the right repo, there are a great very many :)

Please let me know if there are any questions. I tried to explain as best i could.

**Comment by andrross** [comment]
Thanks @drewmiranda-gl! Just curious, are you using the `discovery.type=single-node` setting? I wonder if it makes sense to couple the default number of replicas to this setting as well?

**Comment by williamtrelawny** [comment]
Makes perfect sense to me! At least something like this pseudocode: `if discovery.type=single-node; then number_of_replicas=0; else number_of_replicas=[default]`

**Comment by drewmiranda-gl** [comment]
> Thanks @drewmiranda-gl! Just curious, are you using the `discovery.type=single-node` setting? I wonder if it makes sense to couple the default number of replicas to this setting as well?

Greetings! I am. here is my full opensearch config:

```yml
cluster.name: <redacted>
node.name: <redacted>
path.data: /var/lib/opensearch
path.logs: /var/log/opensearch
transport.host: 0.0.0.0
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
action.auto_create_index: false
plugins.security.disabled: true
path.repo: ["/opt/opensearch/snapshots"]
indices.query.bool.max_clause_count: 2048
```
